services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: anthology
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mysecret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "8080:8080" # host:local
    depends_on:
      - mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data: