# fly.toml app configuration file generated for acl-search on 2024-08-16T21:28:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'acl-search'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
